### ISSUE TITLE
Certified Windows binaries

### ISSUE THREAD

**Issue by System0x40** [ibmruntimes/semeru17-binaries#1]
Hello IBM people.
Thank you for taking care of OpenJ9 builds of AdoptOpenJDK and contributing OpenJ9 itself.
I was wondering if there is any plan for certifed Windows x64 builds?
Also I noticed that you closed the issue section of semeru8-binaries and semeru11-binaries. Where we can ask someone questions like this one, when you close this issue section?

**Comment by AdamBrousseau** [comment]
@mstoodle can you make a comment on Certified Windows.

I have a TODO on my list to add a bit of doc to the ibmruntimes/* semeru repos around raising issues. Short answer is we're going to add a Semeru Issues repo.

**Comment by mstoodle** [comment]
Hi @System0x40 , unfortunately for legal reasons there will be no IBM Semeru Runtime Certified version for the Windows platform. But the Open Edition, which I am happy to say is 100% compatible with the Certified Edition on platforms where they both exist, is available on Windows.
